<a href="https://colab.research.google.com/github/SimranSharma22/Analytics-Projects/blob/main/Simran_py_minor_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Task 1
#Write a program to create your own function similar to built-in function sum() and print the
#sum of numbers present in a list

#Answer:-
def my_sum(lst):
    total = 0
    for num in lst:
        total += num
    return total

# Example usage
my_list = [1, 2, 3, 4, 5]
result = my_sum(my_list)
print(result)


15


In [ ]:
#Task 2
#What is the output of this code snippet?
x = [0, 1, 2, 3, 4]
x.append(x.copy())
print(len(x))

#Answer :-
#The output of the code is 6.
#The last element of x is a list that is a copy of x itself.
#This is because slicing a list using the [:] syntax creates a new list that is a copy of the original list.

6


In [ ]:
#Task 3
#Write a python program to convert temperature from Celsius to Fahrenheit using the if else
#conditions.

#Answer :-
# get temperature in Celsius from user
celsius = float(input("Enter temperature in Celsius: "))

# convert Celsius to Fahrenheit using formula: F = (C * 9/5) + 32
fahrenheit = (celsius * 9/5) + 32

# check if temperature is below freezing point or not
if celsius < 0:
    print("The temperature is below freezing point.")
else:
    print("The temperature is above freezing point.")

# display the result in Fahrenheit
print("Temperature in Fahrenheit:", fahrenheit)



Enter temperature in Celsius: 39
The temperature is above freezing point.
Temperature in Fahrenheit: 102.2


In [ ]:
#Task 4
#Write a python program which will input 5 names from user and print the names in an
#alphabetical order using sequences

#Answer :-
# create an empty list to store the names
names = []

# get 5 names from the user and add them to the list
for i in range(5):
    name = input("Enter a name: ")
    names.append(name)

# sort the list of names in alphabetical order
names.sort()

# print the sorted list of names
print("Names in alphabetical order:")
for name in names:
    print(name)


Enter a name: Simran
Enter a name: Shoaib
Enter a name: Deepa
Enter a name: Bhoomi
Enter a name: Virat
Names in alphabetical order:
Bhoomi
Deepa
Shoaib
Simran
Virat


In [ ]:
#Task 5
#Write a python program to create a numpy array matrix of 5x5 having only odd random
#numbers from 0 to 10

#Answer :-
import numpy as np

# create a 5x5 matrix of random odd numbers between 0 and 10
arr = np.random.randint(0, 6, size=(5, 5)) * 2 + 1

print(arr)


[[ 7  5  7  7  7]
 [ 7  7  3  9  5]
 [ 3  3  7  9 11]
 [ 5  7  7 11  5]
 [ 9  1  3 11  7]]
